# Prerequisites: $DOCKERHUB_USERNAME, $DOCKERHUB_PASSWORD setup as deployment variables
options:
  max-time: 25
  docker: true
  size: 2x

image: atlassian/default-image:3

definitions:
  services:
    docker:
      memory: 7168 # This is the used memory by the Docker daemon(7GB)
  steps:
    - step: &build-deploy
        name: Build and Deploy
        deployment: Staging
        size: 2x # This doubles the amount of resources allocated to the step(8GB)
        caches:
          - docker
        services:
          - docker
        script:
          - IMAGE_NAME=rain_worker
          - IMAGE=${DOCKERHUB_USERNAME}/${IMAGE_NAME}
          - cd ./Worker
          - echo 'Building the image'
          - docker build -t "${IMAGE_NAME}" .
          - echo 'Testing the image'
          - docker run "${IMAGE_NAME}" -c 'import tensorflow as tf; print(tf.__version__)'
          - docker run "${IMAGE_NAME}" -c 'import torch; print(torch.__version__)'
          - echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
          - echo 'Pushing the image'
          - docker tag "${IMAGE_NAME}" "${IMAGE}:${BITBUCKET_TAG}"
          - docker tag "${IMAGE_NAME}" "${IMAGE}:latest"
          - docker push "${IMAGE}:${BITBUCKET_TAG}"
          - docker push "${IMAGE}:latest"
pipelines:
  tags:
    "v*.*.*":
      - step: *build-deploy
       