# Prerequisites: $DOCKERHUB_USERNAME, $DOCKERHUB_PASSWORD setup as deployment variables
options:
  max-time: 25
  docker: true

image: atlassian/default-image:3

pipelines:
  tags:
    "v*.*.*":
      - step:
          name: Build and Deploy to Alpha
          deployment: Staging
          size: 2x
          script:
            - IMAGE_NAME=rain_worker
            - IMAGE=${DOCKERHUB_NAMESPACE}/${IMAGE_NAME}
            - cd ./Worker
            - docker build . --file Dockerfile --tag ${IMAGE_NAME}
            - echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
            - docker tag "${IMAGE_NAME}" "${IMAGE}:${BITBUCKET_TAG}"
            - docker push "${IMAGE}:${BITBUCKET_TAG}"
            - docker tag "${IMAGE_NAME}" "${IMAGE}:latest"
            - docker push "${IMAGE}:latest"
          services:
            - docker
          caches:
            - docker
