# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/coord.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12protos/coord.proto\x12\x05\x63oord\"/\n\x08MetaData\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x11\n\textension\x18\x02 \x01(\t\"L\n\x04\x46ile\x12#\n\x08metadata\x18\x01 \x01(\x0b\x32\x0f.coord.MetaDataH\x00\x12\x14\n\nchunk_data\x18\x02 \x01(\x0cH\x00\x42\t\n\x07request\"\'\n\x14\x44ownloadFileResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"(\n\x12UploadFileResponse\x12\x12\n\nchunk_data\x18\x01 \x01(\x0c\":\n\x10StartLoopMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x15\n\riteration_num\x18\x02 \x01(\x05\"\x1f\n\x0cLoopResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"%\n\x12WorkersInfoRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"V\n\x13WorkersInfoResponse\x12\x13\n\x0bworkers_ips\x18\x01 \x03(\t\x12\x15\n\rworkers_ports\x18\x02 \x03(\x05\x12\x13\n\x0bworkers_ids\x18\x03 \x03(\x05\x32\xce\x01\n\x0b\x63oordinator\x12\x38\n\x08\x64ownload\x12\x0b.coord.File\x1a\x1b.coord.DownloadFileResponse\"\x00(\x01\x12\x38\n\x06upload\x12\x0f.coord.MetaData\x1a\x19.coord.UploadFileResponse\"\x00\x30\x01\x12K\n\x10get_workers_info\x12\x19.coord.WorkersInfoRequest\x1a\x1a.coord.WorkersInfoResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.coord_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _METADATA._serialized_start=29
  _METADATA._serialized_end=76
  _FILE._serialized_start=78
  _FILE._serialized_end=154
  _DOWNLOADFILERESPONSE._serialized_start=156
  _DOWNLOADFILERESPONSE._serialized_end=195
  _UPLOADFILERESPONSE._serialized_start=197
  _UPLOADFILERESPONSE._serialized_end=237
  _STARTLOOPMESSAGE._serialized_start=239
  _STARTLOOPMESSAGE._serialized_end=297
  _LOOPRESPONSE._serialized_start=299
  _LOOPRESPONSE._serialized_end=330
  _WORKERSINFOREQUEST._serialized_start=332
  _WORKERSINFOREQUEST._serialized_end=369
  _WORKERSINFORESPONSE._serialized_start=371
  _WORKERSINFORESPONSE._serialized_end=457
  _COORDINATOR._serialized_start=460
  _COORDINATOR._serialized_end=666
# @@protoc_insertion_point(module_scope)
