syntax = "proto3";
package coord;

service coordinator {
    // to get workers information 
    rpc GetWorkersInfo(WorkersInfoRequest) returns (WorkersInfoResponse) {}
    // to inform coordinator that worker is not responding 
    rpc WorkerNotRespond(WorkerNotRespondRequest) returns (WorkerNotRespondResponse) {}
    rpc GetNWorkers(Request) returns (NumOfWorkers) {}
  }

  // for workers info

  message WorkersInfoRequest {
    string message = 1;
  }

  message WorkersInfoResponse{
    repeated string workers_ips = 1;
    repeated int32 workers_ports = 2;
    repeated int32 workers_ids = 3;
  }

  // for worker not responding  

  message WorkerNotRespondRequest {
    string worker_ip = 1;
    int32 worker_port = 2;
    int32 worker_id = 3;
  }

  message WorkerNotRespondResponse{
    string worker_ip = 1;
    int32 worker_port = 2;
  }

  message Request {
    string message = 1;
  }

  message NumOfWorkers{
    // suggested number of worker must receive from divider
    uint64 NumOfWorkers = 1;
  }
  