# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from Rain.Protos import coord_pb2 as Protos_dot_coord__pb2


class coordinatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetWorkersInfo = channel.unary_unary(
                '/coord.coordinator/GetWorkersInfo',
                request_serializer=Protos_dot_coord__pb2.WorkersInfoRequest.SerializeToString,
                response_deserializer=Protos_dot_coord__pb2.WorkersInfoResponse.FromString,
                )
        self.WorkerNotRespond = channel.unary_unary(
                '/coord.coordinator/WorkerNotRespond',
                request_serializer=Protos_dot_coord__pb2.WorkerNotRespondRequest.SerializeToString,
                response_deserializer=Protos_dot_coord__pb2.WorkerNotRespondResponse.FromString,
                )
        self.GetNWorkers = channel.unary_unary(
                '/coord.coordinator/GetNWorkers',
                request_serializer=Protos_dot_coord__pb2.Request.SerializeToString,
                response_deserializer=Protos_dot_coord__pb2.NumOfWorkers.FromString,
                )


class coordinatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetWorkersInfo(self, request, context):
        """to get workers information 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WorkerNotRespond(self, request, context):
        """to inform coordinator that worker is not responding 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNWorkers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_coordinatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetWorkersInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkersInfo,
                    request_deserializer=Protos_dot_coord__pb2.WorkersInfoRequest.FromString,
                    response_serializer=Protos_dot_coord__pb2.WorkersInfoResponse.SerializeToString,
            ),
            'WorkerNotRespond': grpc.unary_unary_rpc_method_handler(
                    servicer.WorkerNotRespond,
                    request_deserializer=Protos_dot_coord__pb2.WorkerNotRespondRequest.FromString,
                    response_serializer=Protos_dot_coord__pb2.WorkerNotRespondResponse.SerializeToString,
            ),
            'GetNWorkers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNWorkers,
                    request_deserializer=Protos_dot_coord__pb2.Request.FromString,
                    response_serializer=Protos_dot_coord__pb2.NumOfWorkers.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'coord.coordinator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class coordinator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetWorkersInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coord.coordinator/GetWorkersInfo',
            Protos_dot_coord__pb2.WorkersInfoRequest.SerializeToString,
            Protos_dot_coord__pb2.WorkersInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WorkerNotRespond(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coord.coordinator/WorkerNotRespond',
            Protos_dot_coord__pb2.WorkerNotRespondRequest.SerializeToString,
            Protos_dot_coord__pb2.WorkerNotRespondResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNWorkers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coord.coordinator/GetNWorkers',
            Protos_dot_coord__pb2.Request.SerializeToString,
            Protos_dot_coord__pb2.NumOfWorkers.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
