# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from Rain.Protos import divider_pb2 as protos_dot_divider__pb2


class dividerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.upload = channel.unary_stream(
                '/divider.divider/upload',
                request_serializer=protos_dot_divider__pb2.MetaData.SerializeToString,
                response_deserializer=protos_dot_divider__pb2.UploadFileResponse.FromString,
                )
        self.download = channel.stream_unary(
                '/divider.divider/download',
                request_serializer=protos_dot_divider__pb2.File.SerializeToString,
                response_deserializer=protos_dot_divider__pb2.DownloadFileResponse.FromString,
                )


class dividerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def upload(self, request, context):
        """
        send a file to the coordinator contains the file name and the file data.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def download(self, request_iterator, context):
        """
        Recieve a file contains the weights from the workers.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_dividerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'upload': grpc.unary_stream_rpc_method_handler(
                    servicer.upload,
                    request_deserializer=protos_dot_divider__pb2.MetaData.FromString,
                    response_serializer=protos_dot_divider__pb2.UploadFileResponse.SerializeToString,
            ),
            'download': grpc.stream_unary_rpc_method_handler(
                    servicer.download,
                    request_deserializer=protos_dot_divider__pb2.File.FromString,
                    response_serializer=protos_dot_divider__pb2.DownloadFileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'divider.divider', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class divider(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def upload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/divider.divider/upload',
            protos_dot_divider__pb2.MetaData.SerializeToString,
            protos_dot_divider__pb2.UploadFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def download(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/divider.divider/download',
            protos_dot_divider__pb2.File.SerializeToString,
            protos_dot_divider__pb2.DownloadFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
