# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/divider.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protos/divider.proto\x12\x07\x64ivider\"/\n\x08MetaData\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x11\n\textension\x18\x02 \x01(\t\"N\n\x04\x46ile\x12%\n\x08metadata\x18\x01 \x01(\x0b\x32\x11.divider.MetaDataH\x00\x12\x14\n\nchunk_data\x18\x02 \x01(\x0cH\x00\x42\t\n\x07request\"\'\n\x14\x44ownloadFileResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"(\n\x12UploadFileResponse\x12\x12\n\nchunk_data\x18\x01 \x01(\x0c\x32\x85\x01\n\x07\x64ivider\x12<\n\x06upload\x12\x11.divider.MetaData\x1a\x1b.divider.UploadFileResponse\"\x00\x30\x01\x12<\n\x08\x64ownload\x12\r.divider.File\x1a\x1d.divider.DownloadFileResponse\"\x00(\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.divider_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _METADATA._serialized_start=33
  _METADATA._serialized_end=80
  _FILE._serialized_start=82
  _FILE._serialized_end=160
  _DOWNLOADFILERESPONSE._serialized_start=162
  _DOWNLOADFILERESPONSE._serialized_end=201
  _UPLOADFILERESPONSE._serialized_start=203
  _UPLOADFILERESPONSE._serialized_end=243
  _DIVIDER._serialized_start=246
  _DIVIDER._serialized_end=379
# @@protoc_insertion_point(module_scope)
