# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Protos/divider.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14Protos/divider.proto\x12\x07\x64ivider\"/\n\x08MetaData\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x11\n\textension\x18\x02 \x01(\t\"N\n\x04\x46ile\x12%\n\x08metadata\x18\x01 \x01(\x0b\x32\x11.divider.MetaDataH\x00\x12\x14\n\nchunk_data\x18\x02 \x01(\x0cH\x00\x42\t\n\x07request\"\'\n\x14\x44ownloadFileResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"(\n\x12UploadFileResponse\x12\x12\n\nchunk_data\x18\x01 \x01(\x0c\x32\x85\x01\n\x07\x64ivider\x12<\n\x06Upload\x12\x11.divider.MetaData\x1a\x1b.divider.UploadFileResponse\"\x00\x30\x01\x12<\n\x08\x44ownload\x12\r.divider.File\x1a\x1d.divider.DownloadFileResponse\"\x00(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Protos.divider_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_METADATA']._serialized_start=33
  _globals['_METADATA']._serialized_end=80
  _globals['_FILE']._serialized_start=82
  _globals['_FILE']._serialized_end=160
  _globals['_DOWNLOADFILERESPONSE']._serialized_start=162
  _globals['_DOWNLOADFILERESPONSE']._serialized_end=201
  _globals['_UPLOADFILERESPONSE']._serialized_start=203
  _globals['_UPLOADFILERESPONSE']._serialized_end=243
  _globals['_DIVIDER']._serialized_start=246
  _globals['_DIVIDER']._serialized_end=379
# @@protoc_insertion_point(module_scope)
