# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Protos/provisioner.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18Protos/provisioner.proto\x12\tprovision\"\\\n\x0cWorkerStatus\x12\x0b\n\x03IPs\x18\x01 \x03(\t\x12#\n\x08statuses\x18\x02 \x03(\x0e\x32\x11.provision.Status\x12\r\n\x05ports\x18\x03 \x03(\x05\x12\x0b\n\x03ids\x18\x04 \x03(\x05\"$\n\x0cNumOfWorkers\x12\x14\n\x0cNumOfWorkers\x18\x01 \x01(\x04\"\x1b\n\x08response\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x0e\n\x0c\x65mptyMessage\"J\n\rFailureWorker\x12\x11\n\tworker_ip\x18\x01 \x01(\t\x12\x13\n\x0bworker_port\x18\x02 \x01(\x05\x12\x11\n\tworker_id\x18\x03 \x01(\x05\"V\n\tNewWorker\x12\x15\n\rnew_worker_ip\x18\x01 \x01(\t\x12\x17\n\x0fnew_worker_port\x18\x02 \x01(\x05\x12\x19\n\x11new_worker_status\x18\x03 \x01(\x05*\x1a\n\x06Status\x12\x08\n\x04\x44OWN\x10\x00\x12\x06\n\x02UP\x10\x01\x32\xd9\x01\n\x0bprovisioner\x12@\n\nSendStatus\x12\x17.provision.emptyMessage\x1a\x17.provision.WorkerStatus\"\x00\x12@\n\x0e\x44\x65\x66ineNWorkers\x12\x17.provision.NumOfWorkers\x1a\x13.provision.response\"\x00\x12\x46\n\x12SolveFailureWorker\x12\x18.provision.FailureWorker\x1a\x14.provision.NewWorker\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Protos.provisioner_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_STATUS']._serialized_start=380
  _globals['_STATUS']._serialized_end=406
  _globals['_WORKERSTATUS']._serialized_start=39
  _globals['_WORKERSTATUS']._serialized_end=131
  _globals['_NUMOFWORKERS']._serialized_start=133
  _globals['_NUMOFWORKERS']._serialized_end=169
  _globals['_RESPONSE']._serialized_start=171
  _globals['_RESPONSE']._serialized_end=198
  _globals['_EMPTYMESSAGE']._serialized_start=200
  _globals['_EMPTYMESSAGE']._serialized_end=214
  _globals['_FAILUREWORKER']._serialized_start=216
  _globals['_FAILUREWORKER']._serialized_end=290
  _globals['_NEWWORKER']._serialized_start=292
  _globals['_NEWWORKER']._serialized_end=378
  _globals['_PROVISIONER']._serialized_start=409
  _globals['_PROVISIONER']._serialized_end=626
# @@protoc_insertion_point(module_scope)
