# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
from Rain.Protos import worker_pb2 as protos_dot_worker__pb2


class workerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.download = channel.stream_unary(
                '/worker.worker/download',
                request_serializer=protos_dot_worker__pb2.File.SerializeToString,
                response_deserializer=protos_dot_worker__pb2.DownloadFileResponse.FromString,
                )
        self.upload = channel.unary_stream(
                '/worker.worker/upload',
                request_serializer=protos_dot_worker__pb2.MetaData.SerializeToString,
                response_deserializer=protos_dot_worker__pb2.UploadFileResponse.FromString,
                )
        self.Execute = channel.unary_unary(
                '/worker.worker/Execute',
                request_serializer=protos_dot_worker__pb2.executeData.SerializeToString,
                response_deserializer=protos_dot_worker__pb2.ExecuteFileResponse.FromString,
                )


class workerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def download(self, request_iterator, context):
        """worker downloads (recieves) a file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def upload(self, request, context):
        """worker uploads (sends) a file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Execute(self, request, context):
        """execute file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_workerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'download': grpc.stream_unary_rpc_method_handler(
                    servicer.download,
                    request_deserializer=protos_dot_worker__pb2.File.FromString,
                    response_serializer=protos_dot_worker__pb2.DownloadFileResponse.SerializeToString,
            ),
            'upload': grpc.unary_stream_rpc_method_handler(
                    servicer.upload,
                    request_deserializer=protos_dot_worker__pb2.MetaData.FromString,
                    response_serializer=protos_dot_worker__pb2.UploadFileResponse.SerializeToString,
            ),
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=protos_dot_worker__pb2.executeData.FromString,
                    response_serializer=protos_dot_worker__pb2.ExecuteFileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'worker.worker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class worker(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def download(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/worker.worker/download',
            protos_dot_worker__pb2.File.SerializeToString,
            protos_dot_worker__pb2.DownloadFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def upload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/worker.worker/upload',
            protos_dot_worker__pb2.MetaData.SerializeToString,
            protos_dot_worker__pb2.UploadFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/worker.worker/Execute',
            protos_dot_worker__pb2.executeData.SerializeToString,
            protos_dot_worker__pb2.ExecuteFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
