# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/worker.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13protos/worker.proto\x12\x06worker\x1a\x1bgoogle/protobuf/empty.proto\"/\n\x08MetaData\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x11\n\textension\x18\x02 \x01(\t\"M\n\x04\x46ile\x12$\n\x08metadata\x18\x01 \x01(\x0b\x32\x10.worker.MetaDataH\x00\x12\x14\n\nchunk_data\x18\x02 \x01(\x0cH\x00\x42\t\n\x07request\"\'\n\x14\x44ownloadFileResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"(\n\x12UploadFileResponse\x12\x12\n\nchunk_data\x18\x01 \x01(\x0c\"\\\n\x0b\x45xecuteData\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x11\n\textension\x18\x02 \x01(\t\x12\x11\n\tworker_id\x18\x03 \x01(\t\x12\x15\n\riteration_num\x18\x04 \x01(\t\"&\n\x13\x45xecuteFileResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1d\n\nStopSignal\x12\x0f\n\x07message\x18\x01 \x01(\t2\xfb\x01\n\x06worker\x12:\n\x08\x64ownload\x12\x0c.worker.File\x1a\x1c.worker.DownloadFileResponse\"\x00(\x01\x12:\n\x06upload\x12\x10.worker.MetaData\x1a\x1a.worker.UploadFileResponse\"\x00\x30\x01\x12=\n\x07\x45xecute\x12\x13.worker.ExecuteData\x1a\x1b.worker.ExecuteFileResponse\"\x00\x12:\n\nStopWorker\x12\x12.worker.StopSignal\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.worker_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _METADATA._serialized_start=60
  _METADATA._serialized_end=107
  _FILE._serialized_start=109
  _FILE._serialized_end=186
  _DOWNLOADFILERESPONSE._serialized_start=188
  _DOWNLOADFILERESPONSE._serialized_end=227
  _UPLOADFILERESPONSE._serialized_start=229
  _UPLOADFILERESPONSE._serialized_end=269
  _EXECUTEDATA._serialized_start=271
  _EXECUTEDATA._serialized_end=363
  _EXECUTEFILERESPONSE._serialized_start=365
  _EXECUTEFILERESPONSE._serialized_end=403
  _STOPSIGNAL._serialized_start=405
  _STOPSIGNAL._serialized_end=434
  _WORKER._serialized_start=437
  _WORKER._serialized_end=688
# @@protoc_insertion_point(module_scope)
