# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from Rain.Protos import worker_pb2 as Protos_dot_worker__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class workerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Download = channel.stream_unary(
                '/worker.worker/Download',
                request_serializer=Protos_dot_worker__pb2.File.SerializeToString,
                response_deserializer=Protos_dot_worker__pb2.DownloadFileResponse.FromString,
                )
        self.Upload = channel.unary_stream(
                '/worker.worker/Upload',
                request_serializer=Protos_dot_worker__pb2.MetaData.SerializeToString,
                response_deserializer=Protos_dot_worker__pb2.UploadFileResponse.FromString,
                )
        self.Execute = channel.unary_unary(
                '/worker.worker/Execute',
                request_serializer=Protos_dot_worker__pb2.ExecuteData.SerializeToString,
                response_deserializer=Protos_dot_worker__pb2.ExecuteFileResponse.FromString,
                )
        self.StopWorker = channel.unary_unary(
                '/worker.worker/StopWorker',
                request_serializer=Protos_dot_worker__pb2.StopSignal.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class workerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Download(self, request_iterator, context):
        """worker downloads (recieves) a file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Upload(self, request, context):
        """worker Uploads (sends) a file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Execute(self, request, context):
        """execute file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopWorker(self, request, context):
        """to stop a worker serving
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_workerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Download': grpc.stream_unary_rpc_method_handler(
                    servicer.Download,
                    request_deserializer=Protos_dot_worker__pb2.File.FromString,
                    response_serializer=Protos_dot_worker__pb2.DownloadFileResponse.SerializeToString,
            ),
            'Upload': grpc.unary_stream_rpc_method_handler(
                    servicer.Upload,
                    request_deserializer=Protos_dot_worker__pb2.MetaData.FromString,
                    response_serializer=Protos_dot_worker__pb2.UploadFileResponse.SerializeToString,
            ),
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=Protos_dot_worker__pb2.ExecuteData.FromString,
                    response_serializer=Protos_dot_worker__pb2.ExecuteFileResponse.SerializeToString,
            ),
            'StopWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.StopWorker,
                    request_deserializer=Protos_dot_worker__pb2.StopSignal.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'worker.worker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class worker(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Download(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/worker.worker/Download',
            Protos_dot_worker__pb2.File.SerializeToString,
            Protos_dot_worker__pb2.DownloadFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Upload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/worker.worker/Upload',
            Protos_dot_worker__pb2.MetaData.SerializeToString,
            Protos_dot_worker__pb2.UploadFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/worker.worker/Execute',
            Protos_dot_worker__pb2.ExecuteData.SerializeToString,
            Protos_dot_worker__pb2.ExecuteFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/worker.worker/StopWorker',
            Protos_dot_worker__pb2.StopSignal.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
