# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import coord_pb2 as protos_dot_coord__pb2


class coordinatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.download = channel.stream_unary(
                '/coord.coordinator/download',
                request_serializer=protos_dot_coord__pb2.File.SerializeToString,
                response_deserializer=protos_dot_coord__pb2.DownloadFileResponse.FromString,
                )
        self.upload = channel.unary_stream(
                '/coord.coordinator/upload',
                request_serializer=protos_dot_coord__pb2.MetaData.SerializeToString,
                response_deserializer=protos_dot_coord__pb2.UploadFileResponse.FromString,
                )
        self.start_loop = channel.unary_unary(
                '/coord.coordinator/start_loop',
                request_serializer=protos_dot_coord__pb2.StartLoopMessage.SerializeToString,
                response_deserializer=protos_dot_coord__pb2.LoopResponse.FromString,
                )


class coordinatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def download(self, request_iterator, context):
        """coordinator downloads (recieve) a file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def upload(self, request, context):
        """coordinator upload (sends) a file 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def start_loop(self, request, context):
        """coordinator start its loop which sending the data and receiving the model
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_coordinatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'download': grpc.stream_unary_rpc_method_handler(
                    servicer.download,
                    request_deserializer=protos_dot_coord__pb2.File.FromString,
                    response_serializer=protos_dot_coord__pb2.DownloadFileResponse.SerializeToString,
            ),
            'upload': grpc.unary_stream_rpc_method_handler(
                    servicer.upload,
                    request_deserializer=protos_dot_coord__pb2.MetaData.FromString,
                    response_serializer=protos_dot_coord__pb2.UploadFileResponse.SerializeToString,
            ),
            'start_loop': grpc.unary_unary_rpc_method_handler(
                    servicer.start_loop,
                    request_deserializer=protos_dot_coord__pb2.StartLoopMessage.FromString,
                    response_serializer=protos_dot_coord__pb2.LoopResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'coord.coordinator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class coordinator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def download(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/coord.coordinator/download',
            protos_dot_coord__pb2.File.SerializeToString,
            protos_dot_coord__pb2.DownloadFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def upload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/coord.coordinator/upload',
            protos_dot_coord__pb2.MetaData.SerializeToString,
            protos_dot_coord__pb2.UploadFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def start_loop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coord.coordinator/start_loop',
            protos_dot_coord__pb2.StartLoopMessage.SerializeToString,
            protos_dot_coord__pb2.LoopResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
