syntax = "proto3";
package coord;

service coordinator {
    // coordinator downloads (recieve) a file
    rpc download(stream File) returns (DownloadFileResponse) {}
    // coordinator upload (sends) a file 
    rpc upload(MetaData) returns (stream UploadFileResponse) {}
    // coordinator start its loop which sending the data and receiving the model
    rpc start_loop(StartLoopMessage) returns (LoopResponse) {}
    // coordinator stop its loop which sending the data and receiving the model asynchronusly 
    rpc start_loop_async(StartLoopMessageAsync) returns (LoopResponse) {}
  }

  // Define the file metadata message
  message MetaData {
    string filename = 1;
    string extension = 2;
  }
  //------------------
  // for downloading a file
  message File {

    oneof request {
      MetaData metadata = 1;
      bytes chunk_data = 2;
    }
  }
  message DownloadFileResponse {
    string message = 1;
  }
  // ------------------

  // for uploading a file
  message UploadFileResponse {
    bytes chunk_data = 1;
  }
  
  // -------------------
  
  // for loop
  message StartLoopMessage {
    string message = 1;
    int32 iteration_num = 2;
  }
  message LoopResponse {
    string message = 1;
  }
  message StartLoopMessageAsync {
    string message = 1;
    int32 iteration_num = 2;
    int32 worker_id = 3;
  }
  