# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import provisioner_pb2 as protos_dot_provisioner__pb2


class provisionerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendStatus = channel.unary_unary(
                '/provision.provisioner/SendStatus',
                request_serializer=protos_dot_provisioner__pb2.emptyMessage.SerializeToString,
                response_deserializer=protos_dot_provisioner__pb2.WorkerStatus.FromString,
                )
        self.DefineNWorkers = channel.unary_unary(
                '/provision.provisioner/DefineNWorkers',
                request_serializer=protos_dot_provisioner__pb2.NumOfWorkers.SerializeToString,
                response_deserializer=protos_dot_provisioner__pb2.response.FromString,
                )


class provisionerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendStatus(self, request, context):
        """send a Status and IPs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DefineNWorkers(self, request, context):
        """define number of worker
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_provisionerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.SendStatus,
                    request_deserializer=protos_dot_provisioner__pb2.emptyMessage.FromString,
                    response_serializer=protos_dot_provisioner__pb2.WorkerStatus.SerializeToString,
            ),
            'DefineNWorkers': grpc.unary_unary_rpc_method_handler(
                    servicer.DefineNWorkers,
                    request_deserializer=protos_dot_provisioner__pb2.NumOfWorkers.FromString,
                    response_serializer=protos_dot_provisioner__pb2.response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'provision.provisioner', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class provisioner(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/provision.provisioner/SendStatus',
            protos_dot_provisioner__pb2.emptyMessage.SerializeToString,
            protos_dot_provisioner__pb2.WorkerStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DefineNWorkers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/provision.provisioner/DefineNWorkers',
            protos_dot_provisioner__pb2.NumOfWorkers.SerializeToString,
            protos_dot_provisioner__pb2.response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
