# this file is *not* meant to cover or endorse the use of GitHub Actions, but rather to
# help test this project

name: Test

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        python: ['3.8']
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}

    - name: Install Python and Git
      run: sudo apt install -y python3-pip git
    - name: Clone Dependencies gist
      run: git clone https://gist.github.com/Mostafa-wael/ebd011579b7120e336e58671e5239248
    - name: Install Rain Dependencies
      run: |
        python3 -m pip install -U grpcio==1.56.0                                                                                         
        python3 -m pip install -U grpcio-tools==1.56.0                                                                                   
        python3 -m pip install -U protobuf==4.21.6                                                                                  
        python3 -m pip install -U dill==0.3.6                                                                                            
        python3 -m pip install -U numpy==1.22  
        python3 -m pip install -U azure-mgmt-compute==29.1.0                                                                             
        python3 -m pip install -U azure-mgmt-core==1.4.0                                                                                 
        python3 -m pip install -U azure-mgmt-network==23.0.0                                                                             
        python3 -m pip install -U azure-mgmt-resource==23.0.0                                                                            
        python3 -m pip install -U azure-storage-blob==12.13.0                                                                            
        python3 -m pip install -U azure-identity==1.12.0 
        python3 -m pip install -U scikit-learn                                                                               

    - name: Install build dependencies
      run: |
        python3 -m pip install -U setuptools wheel build wheel
        python3 -m pip install twine

    - name: Build the package
      run: python3 -m build .
    - name: Install the package
      run: python3 -m pip install -U dist/*.whl

    - name: Install test dependencies
      run: python3 -m pip install -U tox

    - name: Test
      run: python3 -m tox -e py
